### ISSUE TITLE
GeoParser is unable to parse geographic locations from solr index

### ISSUE THREAD

**Issue by ManasMahanta** [memex-explorer/GeoParser#66]
Below is snippet of my solr index with all required geographic details. 

{"id":"/dev/com/10news/www/42FD5EBC90236148BA72BEC73D622543F282BAF46F05AED2566EE6D7D7BF2A67","Geographic_LONGITUDE":"139.75309","Optional_LONGITUDE":"-87.76142","Optional_NAME":"Mount Carmel","Geographic_LATITUDE":"35.68536","Geographic_NAME":"Japan","Optional_LATITUDE":"38.41088","_version_":1530630356532723712},

After clicking geoparse button on memex home page , the page kind of stuck and returns the following logs in server 

*__Total number of records to be geotagged 6
Generating khooshe tiles..
solr query - http://localhost:8983/solr/hw3/select?q=_%3A*&start=0&rows=500&wt=json
GenerateKhooshe Started..
http://localhost:8983/solr/PolarL_1/select?q=-points%3A%22%5B%5D%22&fl=points,id&wt=json&start=0&rows=50000
Traceback (most recent call last):
  File "/Users/manasranjanmahanta/geoPolar/GeoParser/geoparser_app/solr.py", line 322, in QueryPointsIndex
    if len(response['response']['docs']) == 0:
KeyError: 'response'

'response'
Retrieved 0 points in 0.0258848667145 seconds
Tiles created for 0 Points. Total time 0.0259318351746 seconds
{"responseHeader":{"status":0,"QTime":40}}

[04/Apr/2016 00:03:37] "GET /return_points_khooshe/http://localhost:8983/solr/hw3/PolarL HTTP/1.1" 400 58_**

Can you please tell where the error lies ?

**Comment by smadha** [comment]
This error is actually not causing any trouble as it comes while khooshe
generation. Which must be because there is nothing as of now to generate
points. I just now committed a change to remove these logs to avoid
confusion.

Focus on "query_crawled_index" API in logs. We can help you if you share
your full server console logs through pastebin preferably.

Also as you said your page is stuck mostly your geoparsing must be still running.
Can you see hits in you tika server logs?

Firstly I would recommend to check your setup. i.e. Step 5 in installation

5.MAKE SURE YOU ARE ABLE TO EXTRACT LOCATIONS FROM TIKA SERVER

curl -T /path/to/polar.geot -H "Content-Disposition: attachment;
filename=polar.geot" http://localhost:8001/rmeta

You can obtain file here
https://raw.githubusercontent.com/chrismattmann/geotopicparser-utils/master/geotopics/polar.geot

Output should be this

[
   {
      "Content-Type":"application/geotopic",
      "Geographic_LATITUDE":"39.76",
      "Geographic_LONGITUDE":"-98.5",
      "Geographic_NAME":"United States",
      "Optional_LATITUDE1":"27.33931",
      "Optional_LONGITUDE1":"-108.60288",
      "Optional_NAME1":"China",
      "X-Parsed-By":[
         "org.apache.tika.parser.DefaultParser",
         "org.apache.tika.parser.geo.topic.GeoParser"
      ],
      "X-TIKA:parse_time_millis":"1634",
      "resourceName":"polar.geot"
   }
]

## 

Madhav Sharan

**Comment by ManasMahanta** [comment]
I have attached the details of information you might need .I am able to index the required files with geographic measures but 'memex' is not able to locate points . Can you please tell what i should give input in domain name  & url ?? I have attached screenshot of my details . If there is any wrong in inputs you can please point out ? 

[ServerLogs.pdf](https://github.com/MBoustani/GeoParser/files/201802/ServerLogs.pdf)
[ServerIndex.pdf](https://github.com/MBoustani/GeoParser/files/201803/ServerIndex.pdf)
![screen shot 2016-04-03 at 10 09 20 pm](https://cloud.githubusercontent.com/assets/16406903/14238820/28e58816-f9ea-11e5-8136-b34f867827d4.png)

**Comment by ManasMahanta** [comment]
Sorry for the damaged file . I have attached the correct ones 
[ServerIndex.docx](https://github.com/MBoustani/GeoParser/files/201823/ServerIndex.docx)
[ServerLogs.docx](https://github.com/MBoustani/GeoParser/files/201824/ServerLogs.docx)

**Comment by smadha** [comment]
I can't open any of your files. Can you try [pastebin.com](http://www.pastebin.com)

Before that please share results of step 5 in installation.

`curl -T /path/to/polar.geot -H "Content-Disposition: attachment; filename=polar.geot" http://localhost:8001/rmeta`

**Comment by smadha** [comment]
@Manas007 Is your issue resolved?

**Comment by ManasMahanta** [comment]
Yes, it is resolved .   I was not running two solr servers which are required for Memex GeoParser , got that understanding from previous posted discussions . Memex is up and running . Thanks for your immediate response . It was really helpful .
